server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /media

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Pqn9jlfuzR3+O81KzSInBoW7jhfVlMmMPX864X6RQb3Zb5w7ieG9OGoWR8sqIKFWoJBkWOGPgnM=)
    username: ENC(NO9yEot6aHHgFGVk0xDeinPho+2uGM06)
    password: ENC(Y0nA5ia4HXXcebEGdbZWAlaSYrfjPOi1N6EiMH9m39F8PqsgQY8aWg==)

  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Dialect 설정 추가
        format_sql: true

  profiles:
    include: secret

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha